# Multiple Linear Regression

## Importing the libraries

In [19]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [20]:
dataset = pd.read_csv('heart_failure_clinical_records_dataset.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [21]:
print(X)

[[7.500e+01 0.000e+00 5.820e+02 ... 1.000e+00 0.000e+00 4.000e+00]
 [5.500e+01 0.000e+00 7.861e+03 ... 1.000e+00 0.000e+00 6.000e+00]
 [6.500e+01 0.000e+00 1.460e+02 ... 1.000e+00 1.000e+00 7.000e+00]
 ...
 [4.500e+01 0.000e+00 2.060e+03 ... 0.000e+00 0.000e+00 2.780e+02]
 [4.500e+01 0.000e+00 2.413e+03 ... 1.000e+00 1.000e+00 2.800e+02]
 [5.000e+01 0.000e+00 1.960e+02 ... 1.000e+00 1.000e+00 2.850e+02]]


## Encoding categorical data

In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [23]:
print(X)

[[  1.   0.  75. ...   1.   0.   4.]
 [  1.   0.  55. ...   1.   0.   6.]
 [  1.   0.  65. ...   1.   1.   7.]
 ...
 [  0.   1.  45. ...   0.   0. 278.]
 [  1.   0.  45. ...   1.   1. 280.]
 [  1.   0.  50. ...   1.   1. 285.]]


## Splitting the dataset into the Training set and Test set

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Multiple Linear Regression model on the Training set

In [25]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

## Predicting the Test set results

In [26]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[-4.69e-02  0.00e+00]
 [ 1.82e-01  0.00e+00]
 [ 5.79e-01  1.00e+00]
 [ 1.10e-01  0.00e+00]
 [ 1.89e-01  0.00e+00]
 [ 2.01e-01  0.00e+00]
 [ 5.41e-01  0.00e+00]
 [ 5.23e-02  0.00e+00]
 [ 8.41e-01  1.00e+00]
 [ 4.17e-01  0.00e+00]
 [ 1.77e-01  0.00e+00]
 [ 5.88e-01  1.00e+00]
 [ 2.34e-01  1.00e+00]
 [ 1.71e-01  1.00e+00]
 [ 5.44e-01  1.00e+00]
 [ 6.60e-01  1.00e+00]
 [-8.23e-02  0.00e+00]
 [ 3.88e-01  0.00e+00]
 [ 7.64e-02  0.00e+00]
 [ 9.51e-04  0.00e+00]
 [ 4.05e-01  0.00e+00]
 [ 5.15e-01  0.00e+00]
 [ 5.12e-01  1.00e+00]
 [ 4.41e-01  0.00e+00]
 [ 3.82e-01  1.00e+00]
 [ 1.70e-01  0.00e+00]
 [ 2.20e-01  1.00e+00]
 [-9.33e-02  0.00e+00]
 [-1.59e-01  0.00e+00]
 [ 1.07e-01  0.00e+00]
 [ 1.31e-01  0.00e+00]
 [ 6.67e-01  1.00e+00]
 [ 4.14e-01  1.00e+00]
 [ 4.06e-01  0.00e+00]
 [ 2.63e-01  1.00e+00]
 [ 4.23e-01  1.00e+00]
 [ 2.78e-01  0.00e+00]
 [ 3.94e-01  1.00e+00]
 [-2.91e-01  0.00e+00]
 [ 7.76e-01  1.00e+00]
 [-1.47e-01  0.00e+00]
 [ 4.06e-01  0.00e+00]
 [ 3.23e-01  0.00e+00]
 [ 4.16e-01